name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        architecture: [x64, arm64]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions/setup-rust@v2
      with:
        rust-version: stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Create release
      if: success() && github.event_name == 'push' # Only create a release on successful pushes
      run: |
        TAG=$(date '+%Y%m%d')
        gh release create $TAG --title "Release $TAG" --notes "Automated release created by GitHub Actions."
