name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-rolling, windows-latest]
        architecture: [x64, arm64]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up LLVM and llvm-config
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y llvm-17 llvm-17-dev
        sudo ln -s /usr/bin/llvm-config-17 /usr/bin/llvm-config

    - name: Set up LLVM and llvm-config
      if: matrix.os == 'windows-latest'
      run: |
        choco install llvm --version=17.0.1 -y
        $env:Path += ";C:\Program Files\LLVM\bin"

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Create release
      if: success() && github.event_name == 'push' # Only create a release on successful pushes
      run: |
        TAG=$(date '+%Y%m%d')
        gh release create $TAG --title "Release $TAG" --notes "Automated release created by GitHub Actions."
        
